name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            framework: net8.0
            rid: linux-x64
          - os: windows-latest
            framework: net8.0
            rid: win-x64
          - os: macos-latest
            framework: net8.0
            rid: osx-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet publish IPMage.sln -c Release -r ${{ matrix.rid }} --self-contained

    - name: Upload artifacts for Linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64-binary
        path: '**/bin/Release/net8.0/linux-x64/'

    - name: Upload artifacts for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: win-x64-binary
        path: '**/bin/Release/net8.0/win-x64/'

    - name: Upload artifacts for macOS
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: osx-x64-binary
        path: '**/bin/Release/net8.0/osx-x64/'

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: IPMage-linux-x64
        path: ./binaries/linux-x64/
    
    - name: Download Artifacts for Windows
      uses: actions/download-artifact@v4
      with:
        name: IPMage-win-x64
        path: ./binaries/win-x64/
    
    - name: Download Artifacts for macOS
      uses: actions/download-artifact@v4
      with:
        name: IPMage-osx-x64
        path: ./binaries/osx-x64/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0 #TODO dynamic
        release_name: Release v1.0.0
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binaries/linux-x64/
        asset_name: IPMage-linux-x64.zip
        asset_content_type: application/zip

    - name: Upload Windows Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binaries/win-x64/
        asset_name: IPMage-win-x64.zip
        asset_content_type: application/zip

    - name: Upload macOS Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binaries/osx-x64/
        asset_name: IPMage-osx-x64.zip
        asset_content_type: application/zip
